spring:
  application:
    name: delivery-service
  config:
    import:
      - db.yml
      - rest.yml
      - kafka.yml
      - ssl.yml

server:
  port: 8082

logging:
  level:
    com.sandwich.app: DEBUG

management:
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  endpoints:
    web.exposure:
      include: '*'